CREATE OR REPLACE TABLE MODEL_DEV.RAW_MKTO.ES_ACTIVITIES CLONE MODEL_DEV.RAW_MKTO.ACTIVITIES_RAW;

ALTER TABLE MODEL_DEV.RAW_MKTO.ES_ACTIVITIES ADD COLUMN
  ACTIVITY_TYPE_NAME VARCHAR, DEVICE VARCHAR, EMAIL_CLIENT VARCHAR, LINK_URL VARCHAR, ASSET_ID NUMBER(38,0);

UPDATE MODEL_DEV.RAW_MKTO.ES_ACTIVITIES SET
  ACTIVITY_TYPE_NAME = CASE ACTIVITY_TYPE_ID WHEN 6 THEN 'Send Email' WHEN 7 THEN 'Email Delivered'
       WHEN 8 THEN 'Email Bounced' WHEN 9 THEN 'Unsubscribe' WHEN 10 THEN 'Open Email' WHEN 11 THEN 'Click Email' END,
  DEVICE = CASE WHEN ACTIVITY_TYPE_ID IN (10,11) THEN
       CASE WHEN MOD(ABS(HASH(ACTIVITY_ID)),10)<6 THEN 'Desktop' WHEN MOD(ABS(HASH(ACTIVITY_ID)),10)<9 THEN 'Mobile' ELSE 'Tablet' END END,
  EMAIL_CLIENT = CASE WHEN ACTIVITY_TYPE_ID IN (10,11) THEN
       CASE WHEN MOD(ABS(HASH(ACTIVITY_ID,'ec')),10)<4 THEN 'Gmail' WHEN MOD(ABS(HASH(ACTIVITY_ID,'ec')),10)<7 THEN 'Outlook'
            WHEN MOD(ABS(HASH(ACTIVITY_ID,'ec')),10)<9 THEN 'Apple Mail' ELSE 'Other' END END,
  LINK_URL = CASE WHEN ACTIVITY_TYPE_ID=11 THEN 'https://site.example/' || LOWER(REPLACE(PRIMARY_ATTR_VALUE,' ','-')) END,
  ASSET_ID = PRIMARY_ATTR_VALUE_ID*100 + COALESCE(ATTRIBUTES:send_no::int, 1);

INSERT INTO MODEL_DEV.RAW_MKTO.ES_ACTIVITIES
  (ACTIVITY_ID, LEAD_ID, ACTIVITY_DATE, ACTIVITY_TYPE_ID, PRIMARY_ATTR_VALUE, PRIMARY_ATTR_VALUE_ID, CAMPAIGN_ID,
   ATTRIBUTES, _INGESTED_AT, _SOURCE_BATCH_ID, ACTIVITY_TYPE_NAME, DEVICE, EMAIL_CLIENT, LINK_URL, ASSET_ID)
SELECT ABS(HASH(ACTIVITY_ID,'del')), LEAD_ID, DATEADD('second',2,ACTIVITY_DATE), 7, PRIMARY_ATTR_VALUE, PRIMARY_ATTR_VALUE_ID,
   CAMPAIGN_ID, ATTRIBUTES, _INGESTED_AT, _SOURCE_BATCH_ID, 'Email Delivered', NULL, NULL, NULL, ASSET_ID
FROM MODEL_DEV.RAW_MKTO.ES_ACTIVITIES
WHERE ACTIVITY_TYPE_ID=6 AND MOD(ABS(HASH(ACTIVITY_ID,'bnc')),33)<>0;

INSERT INTO MODEL_DEV.RAW_MKTO.ES_ACTIVITIES
  (ACTIVITY_ID, LEAD_ID, ACTIVITY_DATE, ACTIVITY_TYPE_ID, PRIMARY_ATTR_VALUE, PRIMARY_ATTR_VALUE_ID, CAMPAIGN_ID,
   ATTRIBUTES, _INGESTED_AT, _SOURCE_BATCH_ID, ACTIVITY_TYPE_NAME, DEVICE, EMAIL_CLIENT, LINK_URL, ASSET_ID)
SELECT ABS(HASH(ACTIVITY_ID,'bnc')), LEAD_ID, DATEADD('second',2,ACTIVITY_DATE), 8, PRIMARY_ATTR_VALUE, PRIMARY_ATTR_VALUE_ID,
   CAMPAIGN_ID, ATTRIBUTES, _INGESTED_AT, _SOURCE_BATCH_ID, 'Email Bounced', NULL, NULL, NULL, ASSET_ID
FROM MODEL_DEV.RAW_MKTO.ES_ACTIVITIES
WHERE ACTIVITY_TYPE_ID=6 AND MOD(ABS(HASH(ACTIVITY_ID,'bnc')),33)=0;
